import Image from 'next/image'
import { Inter } from 'next/font/google'
import { SignInButton, SignOutButton } from './components/buttons'
import { Header } from './components/Header'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Minecraft Festival - The easiest way to create <br /> Minecraft music festivals',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
      <main>
        <Header/>

        <p className='text-slate-900 font-extrabold text-3xl lg:text-6xl tracking-tight text-center dark:text-white lg:ml-48 lg:mr-48 lg:mt-24 ml-4 mr-4'>The easiest way to create <br/> Minecraft music festivals.</p>

        <p className='mt-6 text-lg text-slate-600 text-center max-w-3xl lg:mx-auto dark:text-slate-400 m-6'>A feature-packed collaborative editor enabling your team to upload custom music, program show effects and lighting cues, and export your showfiles directly to the server.</p>

        <div className='mt-6 grid place-content-center'>
          <Link href='./dashboard'><button className='rounded-full pl-8 pt-[12px] pr-8 pb-[12px] bg-black text-white dark:bg-white dark:text-black active:scale-95 text-sm'>Open Editor</button></Link>
        </div>

        <img className='w-screen mt-8 mb-8' src="https://pbs.twimg.com/media/Fgq9_xnVIAApIE0?format=jpg&name=large" alt="" />

        <ul className='mt-6 mb-6 text-lg text-slate-600 text-center max-w-3xl mx-auto dark:text-slate-400'>
          <li><Link href='https://rustwasm.github.io/wasm-bindgen/examples/fetch.html' target='_blank'>https://rustwasm.github.io/wasm-bindgen/examples/fetch.html</Link></li>
          <li><Link href='https://github.com/ekzhang/rustpad' target='_blank'>https://github.com/ekzhang/rustpad</Link></li>
          <br/>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Web Assembly + Rust backend</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Next.js frontend</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Documentation page with server setup instructions</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Fetch remote mp3 files</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Fetch hosted openaudio mp3 files</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">OAUTH or github login</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Pocketbase shows database</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Serve shows as json with api and auth-token</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">create a kotlin plugin for downloading showfiles directly to the server</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Websockets to enable real-time collaborative editing</label></li>
        </ul>


      </main>
  )
}
