import Image from 'next/image'
import { Inter } from 'next/font/google'
import { SignInButton } from '../components/buttons'
import { Header } from '../components/Header'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Minecraft Festival - The easiest way to create <br /> Minecraft music festivals',
  description: 'Generated by create next app',
}

export default function Plugin() {
  return (
      <main>
        <Header/>

        <p className='text-slate-900 font-extrabold text-3xl lg:text-6xl tracking-tight text-center dark:text-white lg:ml-48 lg:mr-48 lg:mt-24 lg:ml-4 lg:mr-4 ml-6 mr-6'>Automatically sync <br/> shows with your server</p>

        <div className='m-6 w-screen-6'>
            <img className='rounded lg:mx-auto' src="https://media1.giphy.com/media/52AbBj6Jn0kPKddsgj/giphy.gif?cid=ecf05e47e15b9c0550751d55af21352647decf5427be06fe&ep=v1_gifs_gifId&rid=giphy.gif&ct=g" alt="" />
        </div>
        

        <p className='mt-6 text-lg text-slate-600 text-center max-w-3xl lg:mx-auto dark:text-slate-400 m-6'>Changes you make in the editor are automatically reflected on your server</p>

        <div className='mt-6 grid place-content-center'>
          <Link href='./download'><button className='rounded-full pl-8 pt-[12px] pr-8 pb-[12px] bg-black text-white dark:bg-white dark:text-black active:scale-95 text-sm'>Download</button></Link>
        </div>

        <ul className='mt-6 mb-6 text-lg text-slate-600 text-center max-w-3xl mx-auto dark:text-slate-400'>
          <li><Link href='https://rustwasm.github.io/wasm-bindgen/examples/fetch.html' target='_blank'>https://rustwasm.github.io/wasm-bindgen/examples/fetch.html</Link></li>
          <li><Link href='https://github.com/ekzhang/rustpad' target='_blank'>https://github.com/ekzhang/rustpad</Link></li>
          <br/>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Web Assembly + Rust backend</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Next.js frontend</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Documentation page with server setup instructions</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Fetch remote mp3 files</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Fetch hosted openaudio mp3 files</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">OAUTH or github login</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Pocketbase shows database</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Serve shows as json with api and auth-token</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">create a kotlin plugin for downloading showfiles directly to the server</label></li>
          <li><input className='m-2' type='checkbox'></input><label htmlFor="">Websockets to enable real-time collaborative editing</label></li>
        </ul>


      </main>
  )
}